[project]
name = "cvdemo-backend"
version = "0.0.1"
description = "Teemu's CV site backend"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "python-dotenv"
]

[dependency-groups]
dev = [
    "workers-py",
    "workers-runtime-sdk",
    "fastapi",
    "python-dotenv"
]
